version: "1.0"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3021:3021"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/hotel_booking
      
volumes:
  postgres_data:
