services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: hotel_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  node-app:
    build: .
    ports:
      - 3021:3000
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:pass123@postgres_db:5432/hotel_booking
    networks:
      - app-network
      
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
